### PR TITLE
Fix mac issues

### PR DESCRIPTION
**Pull request by kdheepak**
This will ensure that this package works on Mac assuming that `libklusolve.dylib` is located one level above `libopendssdirect.dylib`.

```bash
deps/apple
├── libklusolve.dylib
├── x64
    └── libopendssdirect.dylib
```

This uses `@loader_path` instead of `@rpath`. I ran the following command

```bash
install_name_tool -change @rpath/libklusolve.dylib @loader_path/../libklusolve.dylib ./deps/apple/x64/libopendssdirect.dylib
```

### CODE REVIEW

**Comment by tshort** [comment]
Awesome!! Tests pass. Finally, you solved the puzzle, @kdheepak :+1: :+1: 

There are some of the old/duplicate dylibs in there. Could you delete those, please? Then, we can finally merge.

**Comment by kdheepak** [comment]
Okay, I've removed duplicates. I've also combined the x64 and x86 libopendssdirect.dylib files, so that there's just one file. I tested this on my machine, this should work on Travis as well. Let me know if any other changes are required to test.

**Comment by kdheepak** [comment]
Just realized I committed some whitespace removal as well, let me know if you want me to undo that.

**Comment by tshort** [comment]
I'm fine with the white space removal. Do you mind rebasing to master? That would check to make sure tests pass on Travis with Julia v0.6.0. Another little thing is that it looks like I got an extra file at `deps/win64/COMProxy_ControlQueue.CSV` that needs to be deleted. (That, I can do later, though.)

**Comment by kdheepak** [comment]
Sure, I'll rebase and submit the PR again. I'm not sure where that file
came from? I'll look into it.

How do I check the status of PRs on your Travis? When I last looked I
wasn't able to see that information. I can set it up on my Travis and look
there though.

Dheepak

On Aug 10, 2017 5:03 AM, "Tom Short" <notifications@github.com> wrote:

I'm fine with the white space removal. Do you mind rebasing to master? That
would check to make sure tests pass on Travis with Julia v0.6.0. Another
little thing is that it looks like I got an extra file at
deps/win64/COMProxy_ControlQueue.CSV that needs to be deleted. (That, I can
do later, though.)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tshort/OpenDSSDirect.jl/pull/20#issuecomment-321520893>,
or mute the thread

**Comment by tshort** [comment]
Shoot. This is happening again. Travis isn't running for some reason. I should show under the green check mark right next to where it shows the AppVeyor run. This also happened with #16. We couldn't figure that out.

**Comment by kdheepak** [comment]
My recollection is that Travis will only run PRs if they can be merged
without conflicts. I didn't think this branch had conflicts though. In
either case, I'll submit a PR with a single (or few) commit(s) starting
from master and we'll see what happens.

**Comment by tshort** [comment]
Hopefully, that's it!

Another tidbit I found in the Travis docs was this bit:

"Travis CI also currently doesn’t build pull requests when the upstream branch is updated. When this happens, GitHub will update the merge commit between the downstream and upstream branch, and send out a notifications. But Travis CI currently ignores this update, as it could lead to a large number of new builds on repositories with lots of pull requests and lots of updates on the upstream branches."

**Comment by kdheepak** [comment]
That's probably it! I'll submit a few PR or test or my Travis account.

**Comment by kdheepak** [comment]
Closing this since this has been resubmitted as a new PR (#21)

**Pull request closed without merging**
