### PR TITLE
A working macOS version

### PR DESCRIPTION
**Pull request by phileas2**
The build and all tests have passed in Travis CI.

https://travis-ci.org/phileas2/OpenDSSDirect.jl

However, I had to omit the built-in sparse solver function `normalsolution_alt()` since it doesn't seem to interact well with `libklusolve.dylib`, which generates a fatal segmentation fault : 

`INFO: Testing OpenDSSDirect
signal (11): Segmentation fault: 11
while loading /Users/travis/.julia/v0.5/OpenDSSDirect/test/lowlevel.jl, in expression starting on line 6
_ZN9KLUSystem12FactorSystemEv at /usr/local/lib/libklusolve.dylib (unknown line)
FactorSparseMatrix at /usr/local/lib/libklusolve.dylib (unknown line)
Allocations: 3441121 (Pool: 3440181; Big: 940); GC: 2
ERROR: OpenDSSDirect had test errors`

### CODE REVIEW

**Comment by tshort** [comment]
Thanks @phileas2! It looks good to me. 

This PR is against the tshort:mac branch. Can you try a PR against the main branch? That way, I think Github will show the results from Travis.

**Comment by tshort** [comment]
Looks like this triggered appveyor but not travis. Any ideas on getting github to run travis?

**Comment by phileas2** [comment]
Unfortunately I have no idea .. maybe the last section of this article will help : 

https://docs.travis-ci.com/user/pull-requests/

**Comment by tshort** [comment]
Could you try pushing a minor change? Maybe that will trigger travis. It'd be good to update the main README to show Mac support.

**Comment by tshort** [comment]
Thanks for the updates! Travis still didn't run. Hmm. That also means the docs don't get updated. I'll try to do some digging. Worst case, I'll merge and try to debug from there.

**Comment by tshort** [comment]
I'm still pondering this, @phileas2. I don't know why Travis isn't working.

In a related development, @kdheepak has developed a similar library for Python. He has updated dylibs for Mac OS, and in Python, he doesn't need to do the copying to /usr/local/lib.

**Comment by phileas2** [comment]
I still can't figure out why it keeps showing "ALL CHECKS have passed", then only mentions the Appveyor check. It means that Github ignores (maybe intentionally) the fact that he must tell Travis the build is mergeable. So perhaps this is a Github issue.

In your repo `Settings > Integration & services > Travis CI,` click on **Test Service** to make sure Github can send the POST file correctly to Travis when an event is triggered.

Make sure also that the box **Active** is checked. If it is not checked, Github will never plan to tell Travis the build is mergeable.

**Comment by kdheepak** [comment]
I'm able to get this package to work in Julia by using the dynamic libraries from @Muxelmann's repository. I've attached a screenshot.

screen shot 2017-08-08 at 11 30 40

**Comment by tshort** [comment]
This is driving me crazy 😓. I've tried many different versions of that with @Muxelmann's libraries. I haven't gotten Travis to pass the tests. Someone else that gets the tests to pass locally may have to try getting Travis to work. I may end up merging this branch (original libs) just to get something working.

**Comment by kdheepak** [comment]
So I tried a fresh install on my personal laptop and I'm currently not able to get it to work. This seems to work on my work laptop though, since I'm able to run OpenDSS using Julia there (I used it for verifying the Python interface). 

I have an unrelated question? How do I clone a repository from Github and make Julia use that repository as the source code when running `using OpenDSSDirect.DSS`? I seem to have now messed up my `~/.julia/` folder, and need to reinstall the package (or at the very least link to it again) since I want to make sure I install the latest source.

**Comment by tshort** [comment]
In Julia, you should be able to do `Pkg.checkout("OpenDSSDirect")` to clone that repo. Use `Pkg.checkout("OpenDSSDirect", "mac")` to get the (nonworking) branch with @Muxelmann's libraries. You can also just manually clone into `~/.julia/v0.6/`. 

If your `~/.julia` folder is borked, you may have to delete it and start over. Then, you need to do `Pkg.add("OpenDSSDirect")` before using the checkout methods above.

**Comment by tshort** [comment]
Closing as we now have a working Mac version from #21 thanks to @kdheepak.

**Pull request closed without merging**
